openapi: '3.1.0'
info:
  title: "JeuxVidéo"
  description: "mon Api sur les jeux Jeux Vidéos"
  version: "1"
servers: 
  - url: "http://localhost:3000/"
    description: "serveur de devloppement"
paths: 
  /api/jeuxvideo/liste:
      get:
        parameters: []
        tags: 
        - "jeuxvideo"
        responses: 
          "200":
            description: "liste de tous les jeux vidéos"
            content: 
              application/json:
                schema:
                  required:
                  - "jeuxvideos"
                  type: "object"
                  properties:
                      jeuxvideos:
                        type: "array"
                        items:
                          required:
                          - "_id"
                          - "nom"
                          - "plateforme"
                          - "dateSortieinitial"
                          - "nombreCopieVendu"
                          - "prix"
                          - "developpeur"
                          - "editeur"
                          - "genre" 
                          - "modeDeJeu"
                          - "dureeJeux"
                          - "disponible"
                          type: "object"
                          properties:
                            _id:
                              type: "string"
                            nom:
                              type: "string"
                            plateforme:
                                type: "array"
                                items:
                                  type: "string"
                            dateSortieinitial:
                              type: "string"
                            nombreCopieVendu:
                              type: "number"
                            prix:
                              type: "number"
                            developpeur:
                              type: "array"
                              items:
                                type: "string"
                            editeur:
                              type: "array"
                              items:
                                type: "string"
                            genre:
                              type: "array"
                              items:
                                type: "string"
                            ESRB:
                              type: "string"
                            modeDeJeu:
                              type: "array"
                              items:
                                type: "string"
                            dureeJeux:
                              type: "number"
                            disponible:
                              type: "boolean"
                            Metacritic:
                              type: "number"
  /api/jeuxvideo/{id}:
    get:
      parameters:
        - in: path
          name: "id"
          schema: 
            type: "string"
          required: true
          description: "l'id du jeux vidéo"
      tags: 
       - "jeuxvideo"
      responses: 
        "200":
            description: " affiche le jeux vidéo avec l'id en paramètre"
            content: 
              application/json:
                schema:
                  required:
                  - "jeuxvideo"
                  type: "object"
                  properties:
                    jeuxvideo:
                      type: "object"
                      properties:
                          _id:
                            type: "string"
                          nom:
                            type: "string"
                          plateforme:
                            type: "array"
                            items:
                              type: "string"
                          dateSortieinitial:
                            type: "string"
                          nombreCopieVendu:
                            type: "number"
                          prix:
                            type: "number"
                          developpeur:
                            type: "array"
                            items:
                              type: "string"
                          editeur:
                            type: "array"
                            items:
                              type: "string"
                          genre:
                            type: "array"
                            items:
                              type: "string"
                          ESRB:
                            type: "string"
                          modeDeJeu:
                            type: "array"
                            items:
                              type: "string"
                          dureeJeux:
                            type: "number"
                          disponible:
                            type: "boolean"
                          Metacritic:
                            type: "number"
        "404": 
          description: " jeux non trouvé avec l'id en paramètre"
          content: 
              application/json:
                schema:
                  required:
                  - "jeuxvideo"
                  type: "object"
                  properties: 
                      jeuxvideo:
                        type: "null"
  /api/genre/{genre}:
    get:
      parameters: 
        - in: path
          name: "genre"
          schema: 
            type: "string"
          required: true
          description: "le genre du jeux vidéo"
      tags: 
        - "jeuxvideo"
      responses:
        "200":
          description: "affiche les jeux en fonction du genre passé en paramètre"
          content:
            application/json: 
              schema: 
                  required: 
                  - "jeuxvideos"
                  type: "object"
                  properties:
                     jeuxvideos:
                      type: "array"
                      items:
                        required:
                        - "_id"
                        - "nom"
                        - "plateforme"
                        - "dateSortieinitial"
                        - "nombreCopieVendu"
                        - "prix"
                        - "developpeur"
                        - "editeur"
                        - "genre" 
                        - "modeDeJeu"
                        - "dureeJeux"
                        - "disponible"
                        type: "object"
                        properties:
                            _id:
                             type: "string"
                            nom:
                              type: "string"
                            plateforme:
                                type: "array"
                                items:
                                  type: "string"
                            dateSortieinitial:
                              type: "string"
                            nombreCopieVendu:
                              type: "number"
                            prix:
                              type: "number"
                            developpeur:
                              type: "array"
                              items:
                                type: "string"
                            editeur:
                              type: "array"
                              items:
                                type: "string"
                            genre:
                              type: "array"
                              items:
                                type: "string"
                            ESRB:
                              type: "string"
                            modeDeJeu:
                              type: "array"
                              items:
                                type: "string"
                            dureeJeux:
                              type: "number"
                            disponible:
                              type: "boolean"
                            Metacritic:
                              type: "number"
        "404":
         description: "aucun jeux trouver avec le paramètre genre"
         content: 
           application/json: 
             schema: 
                 required: 
                 - "jeuxvideo"
                 type: "object"
                 properties: 
                   jeuxvideo:
                    type: "array"
  "/api/jeuxvideo/plateforme/{plateforme}":
     get:
      parameters: 
        - in: path
          name: "plateforme"
          schema: 
            type: "string"
          required: true
          description: "la plateforme du jeux vidéo"
      tags: 
        - "jeuxvideo"
      responses:
        "200":
          description: "affiche les jeux en fonction de la plateforme passé en paramètre"
          content:
            application/json:
              schema: 
                  required: 
                  - "jeuxvideos"
                  type: "object"
                  properties:
                     jeuxvideos:
                      type: "array"
                      items:
                        required:
                        - "_id"
                        - "nom"
                        - "plateforme"
                        - "dateSortieinitial"
                        - "nombreCopieVendu"
                        - "prix"
                        - "developpeur"
                        - "editeur"
                        - "genre" 
                        - "modeDeJeu"
                        - "dureeJeux"
                        - "disponible"
                        type: "object"
                        properties:
                            _id:
                              type: "string"
                            nom:
                              type: "string"
                            plateforme:
                                type: "array"
                                items:
                                  type: "string"
                            dateSortieinitial:
                              type: "string"
                            nombreCopieVendu:
                              type: "number"
                            prix:
                              type: "number"
                            developpeur:
                              type: "array"
                              items:
                                type: "string"
                            editeur:
                              type: "array"
                              items:
                                type: "string"
                            genre:
                              type: "array"
                              items:
                                type: "string"
                            ESRB:
                              type: "string"
                            modeDeJeu:
                              type: "array"
                              items:
                                type: "string"
                            dureeJeux:
                              type: "number"
                            disponible:
                              type: "boolean"
                            Metacritic:
                              type: "number"
        "404":
          description: "aucun jeux trouver avec le paramètre plateforme"
          content: 
           application/json: 
             schema: 
                 required: 
                 - "jeuxvideo"
                 type: "object"
                 properties: 
                   jeuxvideo:
                    type: "array"
  "/api/jeuxvideo/ajouter":
    post: 
      description: "ajoute un jeux avec les information du jeux passé dans le corps de la requete"
      tags: 
        - "jeuxvideo"
      requestBody: 
        content: 
          application/json: 
            schema: 
              required: 
                - "jeuxvideo"
              type: "object"
              properties: 
                jeuxvideo:
                      type: "object"
                      properties:
                          nom:
                            type: "string"
                          plateforme:
                            type: "array"
                            items:
                              type: "string"
                          dateSortieinitial:
                            type: "string"
                          nombreCopieVendu:
                            type: "number"
                          prix:
                            type: "number"
                          developpeur:
                            type: "array"
                            items:
                              type: "string"
                          editeur:
                            type: "array"
                            items:
                              type: "string"
                          genre:
                            type: "array"
                            items:
                              type: "string"
                          ESRB:
                            type: "string"
                          modeDeJeu:
                            type: "array"
                            items:
                              type: "string"
                          dureeJeux:
                            type: "number"
                          disponible:
                            type: "boolean"
                          Metacritic:
                            type: "number"
      responses: 
        "200":
          description: "le jeux est ajouter a la base de donnée"
          content:
            application/json:
              schema:
                required: 
                  - "message"
                type: "object"
                properties:
                    message:
                      type: "string"
        "400":
          description: "paramètre manquant"
          content:
            application/json:
              schema:
                required: 
                  - "errors"
                  - "_message"
                  - "name"
                  - "message"
                type: "object"
                properties: 
                  errors:
                    anyOf: 
                      - $ref: '#/components/schemas/disponible'
                      - $ref: '#/components/schemas/dureeJeux'
                      - $ref: '#/components/schemas/prix'
                      - $ref: '#/components/schemas/nombreCopieVendu'
                      - $ref: '#/components/schemas/dateSortieinitial'
                      - $ref: '#/components/schemas/nom'
                      - $ref: '#/components/schemas/platforme'
                  _message:
                    type: "string"
                  name:
                    type: "string" 
                  message:
                    type: "string"


components: 
  schemas:
    disponible:
      type: "object"
      properties:
        disponible:
          type: "object"
          properties: 
            name:
              type: "string"
            message:
              type: "string"
            "properties":
              type: "object"
              properties: 
                message:
                  type: "string"
                type:
                  type: "string"
                path:
                  type: "string"
            kind:
              type: "string"
            path:
                type: "string"
    dureeJeux:
      type: "object"
      properties:
        dureeJeux:
          type: "object"
          properties: 
            name:
              type: "string"
            message:
              type: "string"
            "properties":
              type: "object"
              properties: 
                message:
                  type: "string"
                type:
                  type: "string"
                path:
                  type: "string"
            kind:
              type: "string"
            path:
                type: "string"
    prix:
      type: "object"
      properties:
        prix:
          type: "object"
          properties: 
            name:
              type: "string"
            message:
              type: "string"
            "properties":
              type: "object"
              properties: 
                message:
                  type: "string"
                type:
                  type: "string"
                path:
                  type: "string"
            kind:
              type: "string"
            path:
                type: "string"
    nombreCopieVendu:
      type: "object"
      properties:
        nombreCopieVendu:
          type: "object"
          properties: 
            name:
              type: "string"
            message:
              type: "string"
            "properties":
              type: "object"
              properties: 
                message:
                  type: "string"
                type:
                  type: "string"
                path:
                  type: "string"
            kind:
              type: "string"
            path:
                type: "string"
    dateSortieinitial:
      type: "object"
      properties:
        dateSortieinitial:
          type: "object"
          properties: 
            name:
              type: "string"
            message:
              type: "string"
            "properties":
              type: "object"
              properties: 
                message:
                  type: "string"
                type:
                  type: "string"
                path:
                  type: "string"
            kind:
              type: "string"
            path:
                type: "string"
    nom:
      type: "object"
      properties:
        nom:
          type: "object"
          properties: 
            name:
              type: "string"
            message:
              type: "string"
            "properties":
              type: "object"
              properties: 
                message:
                  type: "string"
                type:
                  type: "string"
                path:
                  type: "string"
            kind:
              type: "string"
            path:
                type: "string"
    platforme:
      type: "object"
      properties:
        platforme:
          type: "object"
          properties: 
            name:
              type: "string"
            message:
              type: "string"
            "properties":
              type: "object"
              properties: 
                message:
                  type: "string"
                type:
                  type: "string"
                path:
                  type: "string"
                value: 
                  type: "array"
            kind:
              type: "string"
            path:
                type: "string"
            value:
                type: "array"
    

            


        


                
                




              







                  



  









          
                                 

        